import { ReactComponent as MostlyCloudySvg } from './001 Mostly Cloudy_1.svg';
import { ReactComponent as PartlyCloudyNightSvg } from './002 Partly Cloudy Night_1.svg';
import { ReactComponent as BlizzardSvg } from './003 Blizzard_1.svg';
import { ReactComponent as ClearNightSvg } from './004 Clear Night_1.svg';
import { ReactComponent as MostlySunnySvg } from './005 Mostly Sunny_1.svg';
import { ReactComponent as PartlyCloudySvg } from './006 Partly Cloudy_1.svg';
import { ReactComponent as SunsetSvg } from './007 Sunset_1.svg';
import { ReactComponent as SunriseSvg } from './008 Sunrise_1.svg';
import { ReactComponent as HotSvg } from './009 Hot_1.svg';
import { ReactComponent as BreezySvg } from './010 Breezy_1.svg';
import { ReactComponent as RainSvg } from './011 Rain_1.svg';
import { ReactComponent as FogSvg } from './012 Fog_1.svg';
import { ReactComponent as MixRainfallSvg } from './013 Mix Rainfall_1.svg';
import { ReactComponent as SnowSvg } from './014 Snow_1.svg';
import { ReactComponent as ScatteredThundersormSvg } from './015 Scattered Thundersorm_1.svg';
import { ReactComponent as TornadoSvg } from './016 Tornado_1.svg';
import { ReactComponent as TropicalStormSvg } from './017 Tropical Storm_1.svg';
import { ReactComponent as HailSvg } from './018 Hail_1.svg';
import { ReactComponent as BlowingSnowSvg } from './019 Blowing Snow_1.svg';
import { ReactComponent as DrizzleSvg } from './020 Drizzle_1.svg';
import { ReactComponent as DustSvg } from './021 Dust_1.svg';
import { ReactComponent as HurricaneSvg } from './022 Hurricane_1.svg';
import { ReactComponent as ScatteredShowersSvg } from './023 Scattered Showers_1.svg';
import { ReactComponent as SleetSvg } from './024 Sleet_1.svg';
import { ReactComponent as IceSvg } from './025 Ice_1.svg';
import { ReactComponent as HazeSvg } from './026 Haze_1.svg';
import { ReactComponent as SmokeSvg } from './027 Smoke_1.svg';
import { ReactComponent as NoReportSvg } from './028 No Report_1.svg';
import { ReactComponent as HumiditySvg } from './029 Humidity.svg';
import { ReactComponent as AirPressureSvg } from './030 Air_pressure.svg';

import { createIcon } from './Icon';

export const MostlyCloudy = createIcon(<MostlyCloudySvg />);
export const PartlyCloudyNight = createIcon(<PartlyCloudyNightSvg />);
export const Blizzard = createIcon(<BlizzardSvg />);
export const ClearNight = createIcon(<ClearNightSvg />);
export const MostlySunny = createIcon(<MostlySunnySvg />);
export const PartlyCloudy = createIcon(<PartlyCloudySvg />);
export const Sunset = createIcon(<SunsetSvg />);
export const Sunrise = createIcon(<SunriseSvg />);
export const Hot = createIcon(<HotSvg />);
export const Breezy = createIcon(<BreezySvg />);
export const Rain = createIcon(<RainSvg />);
export const Fog = createIcon(<FogSvg />);
export const MixRainfall = createIcon(<MixRainfallSvg />);
export const Snow = createIcon(<SnowSvg />);
export const ScatteredThundersorm = createIcon(<ScatteredThundersormSvg />);
export const Tornado = createIcon(<TornadoSvg />);
export const TropicalStorm = createIcon(<TropicalStormSvg />);
export const Hail = createIcon(<HailSvg />);
export const BlowingSnow = createIcon(<BlowingSnowSvg />);
export const Drizzle = createIcon(<DrizzleSvg />);
export const Dust = createIcon(<DustSvg />);
export const Hurricane = createIcon(<HurricaneSvg />);
export const ScatteredShowers = createIcon(<ScatteredShowersSvg />);
export const Sleet = createIcon(<SleetSvg />);
export const Ice = createIcon(<IceSvg />);
export const Haze = createIcon(<HazeSvg />);
export const Smoke = createIcon(<SmokeSvg />);
export const NoReport = createIcon(<NoReportSvg />);
export const Humidity = createIcon(<HumiditySvg />);
export const AirPressure = createIcon(<AirPressureSvg />);
