name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run eslint
        run: |
            yarn ci
            yarn lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: |
            yarn ci
            yarn build